[package]
name = "retry-after"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies.chrono]
version = "0.2"
git = "https://github.com/lifthrasiir/rust-chrono"
rev = "ada7aeda72bd4b6e8439419b36a9de192286a94c"

[dependencies.hyper]
version = "0.7"
default-features = false

[dev-dependencies]
httparse = "*"
