[package]
name = "retry-after"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies.chrono]
version = "0.2.21"

[dependencies.hyper]
version = "0.7"
default-features = false

[dev-dependencies]
httparse = "*"
